using Microsoft.Extensions.DependencyInjection;
using Nikse.SubtitleEdit.Features.Assa;
using Nikse.SubtitleEdit.Features.Edit.AlignmentPicker;
using Nikse.SubtitleEdit.Features.Edit.Find;
using Nikse.SubtitleEdit.Features.Edit.ModifySelection;
using Nikse.SubtitleEdit.Features.Edit.MultipleReplace;
using Nikse.SubtitleEdit.Features.Edit.Replace;
using Nikse.SubtitleEdit.Features.Edit.ShowHistory;
using Nikse.SubtitleEdit.Features.Files.Compare;
using Nikse.SubtitleEdit.Features.Files.Export.ExportEbuStl;
using Nikse.SubtitleEdit.Features.Files.ExportCavena890;
using Nikse.SubtitleEdit.Features.Files.ExportCustomTextFormat;
using Nikse.SubtitleEdit.Features.Files.ExportImageBased;
using Nikse.SubtitleEdit.Features.Files.ExportPac;
using Nikse.SubtitleEdit.Features.Files.ExportPlainText;
using Nikse.SubtitleEdit.Features.Files.ManualChosenEncoding;
using Nikse.SubtitleEdit.Features.Files.RestoreAutoBackup;
using Nikse.SubtitleEdit.Features.Files.Statistics;
using Nikse.SubtitleEdit.Features.Main;
using Nikse.SubtitleEdit.Features.Main.ColumnPaste;
using Nikse.SubtitleEdit.Features.Main.Layout;
using Nikse.SubtitleEdit.Features.Ocr;
using Nikse.SubtitleEdit.Features.Ocr.Download;
using Nikse.SubtitleEdit.Features.Ocr.FixEngine;
using Nikse.SubtitleEdit.Features.Ocr.NOcr;
using Nikse.SubtitleEdit.Features.Options.Language;
using Nikse.SubtitleEdit.Features.Options.Settings;
using Nikse.SubtitleEdit.Features.Options.Shortcuts;
using Nikse.SubtitleEdit.Features.Options.WordLists;
using Nikse.SubtitleEdit.Features.Shared;
using Nikse.SubtitleEdit.Features.Shared.AddToNamesList;
using Nikse.SubtitleEdit.Features.Shared.AddToOcrReplaceList;
using Nikse.SubtitleEdit.Features.Shared.AddToUserDictionary;
using Nikse.SubtitleEdit.Features.Shared.Bookmarks;
using Nikse.SubtitleEdit.Features.Shared.FindText;
using Nikse.SubtitleEdit.Features.Shared.GoToLineNumber;
using Nikse.SubtitleEdit.Features.Shared.PickAlignment;
using Nikse.SubtitleEdit.Features.Shared.PickColor;
using Nikse.SubtitleEdit.Features.Shared.PickFontName;
using Nikse.SubtitleEdit.Features.Shared.PickLayers;
using Nikse.SubtitleEdit.Features.Shared.PickMatroskaTrack;
using Nikse.SubtitleEdit.Features.Shared.PickMp4Track;
using Nikse.SubtitleEdit.Features.Shared.PickRuleProfile;
using Nikse.SubtitleEdit.Features.Shared.PromptTextBox;
using Nikse.SubtitleEdit.Features.Shared.ShowImage;
using Nikse.SubtitleEdit.Features.Shared.SourceView;
using Nikse.SubtitleEdit.Features.Shared.WaveformGuessTimeCodes;
using Nikse.SubtitleEdit.Features.Shared.WaveformSeekSilence;
using Nikse.SubtitleEdit.Features.SpellCheck;
using Nikse.SubtitleEdit.Features.SpellCheck.EditWholeText;
using Nikse.SubtitleEdit.Features.SpellCheck.GetDictionaries;
using Nikse.SubtitleEdit.Features.Sync.AdjustAllTimes;
using Nikse.SubtitleEdit.Features.Sync.ChangeFrameRate;
using Nikse.SubtitleEdit.Features.Sync.ChangeSpeed;
using Nikse.SubtitleEdit.Features.Sync.VisualSync;
using Nikse.SubtitleEdit.Features.Tools.AdjustDuration;
using Nikse.SubtitleEdit.Features.Tools.ApplyDurationLimits;
using Nikse.SubtitleEdit.Features.Tools.ApplyMinGap;
using Nikse.SubtitleEdit.Features.Tools.BatchConvert;
using Nikse.SubtitleEdit.Features.Tools.BridgeGaps;
using Nikse.SubtitleEdit.Features.Tools.ChangeCasing;
using Nikse.SubtitleEdit.Features.Tools.FixCommonErrors;
using Nikse.SubtitleEdit.Features.Tools.JoinSubtitles;
using Nikse.SubtitleEdit.Features.Tools.MergeShortLines;
using Nikse.SubtitleEdit.Features.Tools.MergeSubtitlesWithSameText;
using Nikse.SubtitleEdit.Features.Tools.MergeSubtitlesWithSameTimeCodes;
using Nikse.SubtitleEdit.Features.Tools.RemoveTextForHearingImpaired;
using Nikse.SubtitleEdit.Features.Tools.SplitBreakLongLines;
using Nikse.SubtitleEdit.Features.Tools.SplitSubtitle;
using Nikse.SubtitleEdit.Features.Translate;
using Nikse.SubtitleEdit.Features.Video.AudioToTextWhisper;
using Nikse.SubtitleEdit.Features.Video.BlankVideo;
using Nikse.SubtitleEdit.Features.Video.BurnIn;
using Nikse.SubtitleEdit.Features.Video.CutVideo;
using Nikse.SubtitleEdit.Features.Video.GoToVideoPosition;
using Nikse.SubtitleEdit.Features.Video.OpenFromUrl;
using Nikse.SubtitleEdit.Features.Video.ReEncodeVideo;
using Nikse.SubtitleEdit.Features.Video.ShotChanges;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.DownloadTts;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.ElevenLabsSettings;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.EncodingSettings;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.VoiceSettings;
using Nikse.SubtitleEdit.Features.Video.TransparentSubtitles;
using Nikse.SubtitleEdit.Logic;
using Nikse.SubtitleEdit.Logic.Compression;
using Nikse.SubtitleEdit.Logic.Dictionaries;
using Nikse.SubtitleEdit.Logic.Download;
using Nikse.SubtitleEdit.Logic.Initializers;
using Nikse.SubtitleEdit.Logic.Media;
using Nikse.SubtitleEdit.Logic.UndoRedo;
using ReviewSpeechViewModel = Nikse.SubtitleEdit.Features.Video.TextToSpeech.ReviewSpeech.ReviewSpeechViewModel;

namespace Nikse.SubtitleEdit;

public static class DependencyInjectionExtensions
{
    public static void AddSubtitleEditServices(this IServiceCollection collection)
    {
        // Misc services        
        collection.AddSingleton<IFileHelper, FileHelper>();
        collection.AddSingleton<IFolderHelper, FolderHelper>();
        collection.AddTransient<IAutoBackupService, AutoBackupService>();
        collection.AddTransient<IBatchConverter, BatchConverter>();
        collection.AddTransient<IBluRayHelper, BluRayHelper>();
        collection.AddTransient<IDictionaryInitializer, DictionaryInitializer>();
        collection.AddTransient<IFindService, FindService>();
        collection.AddTransient<IInsertService, InsertService>();
        collection.AddTransient<ILanguageInitializer, LanguageInitializer>();
        collection.AddTransient<IMergeManager, MergeManager>();
        collection.AddTransient<IMpvReloader, MpvReloader>();
        collection.AddTransient<INOcrCaseFixer, NOcrCaseFixer>();
        collection.AddTransient<INamesList, SeNamesList>();
        collection.AddTransient<IOcrInitializer, OcrInitializer>();
        collection.AddTransient<IShortcutManager, ShortcutManager>();
        collection.AddTransient<ISpellCheckManager, SpellCheckManager>();
        collection.AddTransient<ISplitManager, SplitManager>();
        collection.AddTransient<IThemeInitializer, ThemeInitializer>();
        collection.AddTransient<ITtsDownloadService, TtsDownloadService>();
        collection.AddTransient<IUndoRedoManager, UndoRedoManager>();
        collection.AddTransient<IWindowService, WindowService>();
        collection.AddTransient<IZipUnpacker, ZipUnpacker>();
        collection.AddTransient<IColorService, ColorService>();
        collection.AddTransient<IFontNameService, FontNameService>();
        collection.AddTransient<IOcrFixEngine2, OcrFixEngine2>();

        // Download services
        collection.AddHttpClient<IFfmpegDownloadService, FfmpegDownloadService>();
        collection.AddHttpClient<ILibMpvDownloadService, LibMpvDownloadService>();
        collection.AddHttpClient<IPaddleOcrDownloadService, PaddleOcrDownloadService>();
        collection.AddHttpClient<ISpellCheckDictionaryDownloadService, SpellCheckDictionaryDownloadService>();
        collection.AddHttpClient<ITesseractDownloadService, TesseractDownloadService>();
        collection.AddHttpClient<IWhisperDownloadService, WhisperDownloadService>();

        // Window view models
        collection.AddTransient<AddToNamesListViewModel>();
        collection.AddTransient<AddToOcrReplaceListViewModel>();
        collection.AddTransient<AddToUserDictionaryViewModel>();
        collection.AddTransient<AdjustAllTimesViewModel>();
        collection.AddTransient<AdjustDurationViewModel>();
        collection.AddTransient<ApplyDurationLimitsViewModel>();
        collection.AddTransient<ApplyMinGapViewModel>();
        collection.AddTransient<AlignmentPickerViewModel>();
        collection.AddTransient<AssaAttachmentsViewModel>();
        collection.AddTransient<AssaPropertiesViewModel>();
        collection.AddTransient<AssaStylePickerViewModel>();
        collection.AddTransient<AssaStylesViewModel>();
        collection.AddTransient<AudioToTextWhisperViewModel>();
        collection.AddTransient<AudioVisualizerUndockedViewModel>();
        collection.AddTransient<AutoTranslateViewModel>();
        collection.AddTransient<BatchConvertSettingsViewModel>();
        collection.AddTransient<BatchConvertViewModel>();
        collection.AddTransient<BlankVideoViewModel>();
        collection.AddTransient<BookmarkEditViewModel>();
        collection.AddTransient<BookmarksListViewModel>();
        collection.AddTransient<BridgeGapsViewModel>();
        collection.AddTransient<BurnInEffectViewModel>();
        collection.AddTransient<BurnInResolutionPickerViewModel>();
        collection.AddTransient<BurnInSettingsViewModel>();
        collection.AddTransient<BurnInViewModel>();
        collection.AddTransient<ChangeCasingViewModel>();
        collection.AddTransient<ChangeFrameRateViewModel>();
        collection.AddTransient<ChangeSpeedViewModel>();
        collection.AddTransient<ColumnPasteViewModel>();
        collection.AddTransient<CompareViewModel>();
        collection.AddTransient<CopyPasteTranslateBlockViewModel>();
        collection.AddTransient<CopyPasteTranslateViewModel>();
        collection.AddTransient<CustomContinuationStyleViewModel>();
        collection.AddTransient<CutVideoViewModel>();
        collection.AddTransient<DownloadFfmpegViewModel>();
        collection.AddTransient<DownloadLibMpvViewModel>();
        collection.AddTransient<DownloadPaddleOcrViewModel>();
        collection.AddTransient<DownloadTesseractModelViewModel>();
        collection.AddTransient<DownloadTesseractViewModel>();
        collection.AddTransient<DownloadTtsViewModel>();
        collection.AddTransient<DownloadWhisperEngineViewModel>();
        collection.AddTransient<DownloadWhisperModelsViewModel>();
        collection.AddTransient<EditCategoryViewModel>();
        collection.AddTransient<EditCustomTextFormatViewModel>();
        collection.AddTransient<EditRuleViewModel>();
        collection.AddTransient<EditWholeTextViewModel>();
        collection.AddTransient<ElevenLabsSettingsViewModel>();
        collection.AddTransient<EncodingSettingsViewModel>();
        collection.AddTransient<ExportCavena890ViewModel>();
        collection.AddTransient<ExportCustomTextFormatViewModel>();
        collection.AddTransient<ExportEbuStlViewModel>();
        collection.AddTransient<ExportImageBasedViewModel>();
        collection.AddTransient<ExportPacViewModel>();
        collection.AddTransient<ExportPlainTextViewModel>();
        collection.AddTransient<FindTextViewModel>();
        collection.AddTransient<FindViewModel>();
        collection.AddTransient<FixCommonErrorsProfileViewModel>();
        collection.AddTransient<FixCommonErrorsViewModel>();
        collection.AddTransient<FixNamesViewModel>();
        collection.AddTransient<GetDictionariesViewModel>();
        collection.AddTransient<GetKeyViewModel>();
        collection.AddTransient<GoToLineNumberViewModel>();
        collection.AddTransient<GoToVideoPositionViewModel>();
        collection.AddTransient<ImageBasedPreviewViewModel>();
        collection.AddTransient<ImageBasedProfileViewModel>();
        collection.AddTransient<InterjectionsViewModel>();
        collection.AddTransient<JoinSubtitlesViewModel>();
        collection.AddTransient<LanguageViewModel>();
        collection.AddTransient<LayoutViewModel>();
        collection.AddTransient<MainView>();
        collection.AddTransient<MainViewModel>();
        collection.AddTransient<ManualChosenEncodingViewModel>();
        collection.AddTransient<MergeSameTextViewModel>();
        collection.AddTransient<MergeSameTimeCodesViewModel>();
        collection.AddTransient<MergeShortLinesViewModel>();
        collection.AddTransient<ModifySelectionViewModel>();
        collection.AddTransient<MultipleReplaceViewModel>();
        collection.AddTransient<NOcrCharacterAddViewModel>();
        collection.AddTransient<NOcrCharacterHistoryViewModel>();
        collection.AddTransient<NOcrDbEditViewModel>();
        collection.AddTransient<NOcrDbNewViewModel>();
        collection.AddTransient<NOcrInspectViewModel>();
        collection.AddTransient<NOcrSettingsViewModel>();
        collection.AddTransient<OcrViewModel>();
        collection.AddTransient<OpenFromUrlViewModel>();
        collection.AddTransient<PartsSavedViewModel>();
        collection.AddTransient<PickAlignmentViewModel>();
        collection.AddTransient<PickColorViewModel>();
        collection.AddTransient<PickFontNameViewModel>();
        collection.AddTransient<PickLayersViewModel>();
        collection.AddTransient<PickMatroskaTrackViewModel>();
        collection.AddTransient<PickOllamaModelViewModel>();
        collection.AddTransient<PickMp4TrackViewModel>();
        collection.AddTransient<PickRuleProfileViewModel>();
        collection.AddTransient<PreProcessingViewModel>();
        collection.AddTransient<ProfilesExportViewModel>();
        collection.AddTransient<ProfilesViewModel>();
        collection.AddTransient<PromptTextBoxViewModel>();
        collection.AddTransient<PromptUnknownWordViewModel>();
        collection.AddTransient<ReEncodeVideoViewModel>();
        collection.AddTransient<RemoveTextForHearingImpairedViewModel>();
        collection.AddTransient<ReplaceViewModel>();
        collection.AddTransient<RestoreAutoBackupViewModel>();
        collection.AddTransient<ReviewSpeechViewModel>();
        collection.AddTransient<SelectVideoPositionViewModel>();
        collection.AddTransient<SettingsResetViewModel>();
        collection.AddTransient<SettingsViewModel>();
        collection.AddTransient<ShotChangeListViewModel>();
        collection.AddTransient<ShotChangesViewModel>();
        collection.AddTransient<ShortcutsViewModel>();
        collection.AddTransient<ShowHistoryViewModel>();
        collection.AddTransient<ShowImageViewModel>();
        collection.AddTransient<SourceViewViewModel>();
        collection.AddTransient<SpellCheckViewModel>();
        collection.AddTransient<SplitBreakLongLinesViewModel>();
        collection.AddTransient<SplitSubtitleViewModel>();
        collection.AddTransient<StatisticsViewModel>();
        collection.AddTransient<TextToSpeechViewModel>();
        collection.AddTransient<TranslateSettingsViewModel>();
        collection.AddTransient<TransparentSettingsViewModel>();
        collection.AddTransient<TransparentSubtitlesViewModel>();
        collection.AddTransient<VideoPlayerUndockedViewModel>();
        collection.AddTransient<VisualSyncViewModel>();
        collection.AddTransient<VoiceSettingsViewModel>();
        collection.AddTransient<WaveformGuessTimeCodesViewModel>();
        collection.AddTransient<WaveformSeekSilenceViewModel>();
        collection.AddTransient<WhisperAdvancedViewModel>();
        collection.AddTransient<WhisperPostProcessingViewModel>();
        collection.AddTransient<WordListsViewModel>();
    }
}