using Microsoft.Extensions.DependencyInjection;
using Nikse.SubtitleEdit.Features.Edit.AlignmentPicker;
using Nikse.SubtitleEdit.Features.Edit.Find;
using Nikse.SubtitleEdit.Features.Edit.GoToLineNumber;
using Nikse.SubtitleEdit.Features.Edit.MultipleReplace;
using Nikse.SubtitleEdit.Features.Edit.Replace;
using Nikse.SubtitleEdit.Features.Edit.ShowHistory;
using Nikse.SubtitleEdit.Features.Files.Export.ExportEbuStl;
using Nikse.SubtitleEdit.Features.Files.ExportCavena890;
using Nikse.SubtitleEdit.Features.Files.ExportImageBased;
using Nikse.SubtitleEdit.Features.Files.ExportPac;
using Nikse.SubtitleEdit.Features.Files.RestoreAutoBackup;
using Nikse.SubtitleEdit.Features.Main;
using Nikse.SubtitleEdit.Features.Main.Layout;
using Nikse.SubtitleEdit.Features.Options.Language;
using Nikse.SubtitleEdit.Features.Options.Settings;
using Nikse.SubtitleEdit.Features.Options.Shortcuts;
using Nikse.SubtitleEdit.Features.Shared;
using Nikse.SubtitleEdit.Features.Shared.Ocr;
using Nikse.SubtitleEdit.Features.Shared.PickMatroskaTrack;
using Nikse.SubtitleEdit.Features.SpellCheck;
using Nikse.SubtitleEdit.Features.SpellCheck.EditWholeText;
using Nikse.SubtitleEdit.Features.SpellCheck.GetDictionaries;
using Nikse.SubtitleEdit.Features.Sync.AdjustAllTimes;
using Nikse.SubtitleEdit.Features.Sync.ChangeFrameRate;
using Nikse.SubtitleEdit.Features.Sync.ChangeSpeed;
using Nikse.SubtitleEdit.Features.Tools.AdjustDuration;
using Nikse.SubtitleEdit.Features.Tools.BatchConvert;
using Nikse.SubtitleEdit.Features.Tools.ChangeCasing;
using Nikse.SubtitleEdit.Features.Tools.FixCommonErrors;
using Nikse.SubtitleEdit.Features.Tools.RemoveTextForHearingImpaired;
using Nikse.SubtitleEdit.Features.Translate;
using Nikse.SubtitleEdit.Features.Video.AudioToTextWhisper;
using Nikse.SubtitleEdit.Features.Video.BurnIn;
using Nikse.SubtitleEdit.Features.Video.OpenFromUrl;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.DownloadTts;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.ElevenLabsSettings;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.EncodingSettings;
using Nikse.SubtitleEdit.Features.Video.TextToSpeech.VoiceSettings;
using Nikse.SubtitleEdit.Features.Video.TransparentSubtitles;
using Nikse.SubtitleEdit.Logic;
using Nikse.SubtitleEdit.Logic.Compression;
using Nikse.SubtitleEdit.Logic.Dictionaries;
using Nikse.SubtitleEdit.Logic.Download;
using Nikse.SubtitleEdit.Logic.Initializers;
using Nikse.SubtitleEdit.Logic.Media;
using Nikse.SubtitleEdit.Logic.UndoRedo;

namespace Nikse.SubtitleEdit;

public static class DependencyInjectionExtensions
{
    public static void AddCommonServices(this IServiceCollection collection)
    {
        // Misc services
        collection.AddSingleton<IFileHelper, FileHelper>();
        collection.AddSingleton<IFolderHelper, FolderHelper>();
        collection.AddTransient<IAutoBackupService, AutoBackupService>();
        collection.AddTransient<IBatchConverter, BatchConverter>();
        collection.AddTransient<IBluRayHelper, BluRayHelper>();
        collection.AddTransient<IDictionaryInitializer, DictionaryInitializer>();
        collection.AddTransient<IFindService, FindService>();
        collection.AddTransient<IInsertService, InsertService>();
        collection.AddTransient<ILanguageInitializer, LanguageInitializer>();
        collection.AddTransient<IMergeManager, MergeManager>();
        collection.AddTransient<IMpvReloader, MpvReloader>();
        collection.AddTransient<INOcrCaseFixer, NOcrCaseFixer>();
        collection.AddTransient<INamesList, SeNamesList>();
        collection.AddTransient<IOcrInitializer, OcrInitializer>();
        collection.AddTransient<IShortcutManager, ShortcutManager>();
        collection.AddTransient<ISpellCheckManager, SpellCheckManager>();
        collection.AddTransient<ISplitManager, SplitManager>();
        collection.AddTransient<IThemeInitializer, ThemeInitializer>();
        collection.AddTransient<ITtsDownloadService, TtsDownloadService>();
        collection.AddTransient<IUndoRedoManager, UndoRedoManager>();
        collection.AddTransient<IWindowService, WindowService>();
        collection.AddTransient<IZipUnpacker, ZipUnpacker>();

        // Download services
        collection.AddHttpClient<IFfmpegDownloadService, FfmpegDownloadService>();
        collection.AddHttpClient<ILibMpvDownloadService, LibMpvDownloadService>();
        collection.AddHttpClient<IPaddleOcrDownloadService, PaddleOcrDownloadService>();
        collection.AddHttpClient<ISpellCheckDictionaryDownloadService, SpellCheckDictionaryDownloadService>();
        collection.AddHttpClient<ITesseractDownloadService, TesseractDownloadService>();
        collection.AddHttpClient<IWhisperDownloadService, WhisperDownloadService>(); ;

        // Window view models
        collection.AddTransient<AdjustAllTimesViewModel>();
        collection.AddTransient<AdjustDurationViewModel>();
        collection.AddTransient<AlignmentPickerViewModel>();
        collection.AddTransient<AudioToTextWhisperViewModel>();
        collection.AddTransient<AutoTranslateViewModel>();
        collection.AddTransient<BatchConvertSettingsViewModel>();
        collection.AddTransient<BatchConvertViewModel>();
        collection.AddTransient<BurnInResolutionPickerViewModel>();
        collection.AddTransient<BurnInSettingsViewModel>();
        collection.AddTransient<BurnInViewModel>();
        collection.AddTransient<ChangeCasingViewModel>();
        collection.AddTransient<ChangeFrameRateViewModel>();
        collection.AddTransient<ChangeSpeedViewModel>();
        collection.AddTransient<DownloadFfmpegViewModel>();
        collection.AddTransient<DownloadLibMpvViewModel>();
        collection.AddTransient<DownloadPaddleOcrViewModel>();
        collection.AddTransient<DownloadTesseractModelViewModel>();
        collection.AddTransient<DownloadTesseractViewModel>();
        collection.AddTransient<DownloadTtsViewModel>();
        collection.AddTransient<DownloadWhisperEngineViewModel>();
        collection.AddTransient<DownloadWhisperModelsViewModel>();
        collection.AddTransient<EditCategoryViewModel>();
        collection.AddTransient<EditRuleViewModel>();
        collection.AddTransient<EditWholeTextViewModel>();
        collection.AddTransient<ElevenLabsSettingsViewModel>();
        collection.AddTransient<EncodingSettingsViewModel>();
        collection.AddTransient<ExportCavena890ViewModel>();
        collection.AddTransient<ExportEbuStlViewModel>();
        collection.AddTransient<ExportImageBasedViewModel>();
        collection.AddTransient<ExportPacViewModel>();
        collection.AddTransient<FindViewModel>();
        collection.AddTransient<FixCommonErrorsProfileViewModel>();
        collection.AddTransient<FixCommonErrorsViewModel>();
        collection.AddTransient<FixNamesViewModel>();
        collection.AddTransient<GetDictionariesViewModel>();
        collection.AddTransient<GetKeyViewModel>();
        collection.AddTransient<GoToLineNumberViewModel>();
        collection.AddTransient<GoToVideoPositionViewModel>();
        collection.AddTransient<ImageBasedPreviewViewModel>();
        collection.AddTransient<ImageBasedProfileViewModel>();
        collection.AddTransient<InterjectionsViewModel>();
        collection.AddTransient<LanguageViewModel>();
        collection.AddTransient<LayoutViewModel>();
        collection.AddTransient<MainView>();
        collection.AddTransient<MainViewModel>();
        collection.AddTransient<MultipleReplaceViewModel>();
        collection.AddTransient<NOcrCharacterAddViewModel>();
        collection.AddTransient<NOcrCharacterHistoryViewModel>();
        collection.AddTransient<NOcrDbEditViewModel>();
        collection.AddTransient<NOcrDbNewViewModel>();
        collection.AddTransient<NOcrInspectViewModel>();
        collection.AddTransient<NOcrSettingsViewModel>();
        collection.AddTransient<OcrViewModel>();
        collection.AddTransient<OllamaBrowseViewModel>();
        collection.AddTransient<OpenFromUrlViewModel>();
        collection.AddTransient<PickMatroskaTrackViewModel>();
        collection.AddTransient<RemoveTextForHearingImpairedViewModel>();
        collection.AddTransient<ReplaceViewModel>();
        collection.AddTransient<RestoreAutoBackupViewModel>();
        collection.AddTransient<ReviewSpeechViewModel>();
        collection.AddTransient<SelectVideoPositionViewModel>();
        collection.AddTransient<SettingsViewModel>();
        collection.AddTransient<ShortcutsViewModel>();
        collection.AddTransient<ShowHistoryViewModel>();
        collection.AddTransient<SpellCheckViewModel>();
        collection.AddTransient<TextToSpeechViewModel>();
        collection.AddTransient<TranslateSettingsViewModel>();
        collection.AddTransient<TransparentSettingsViewModel>();
        collection.AddTransient<TransparentSubtitlesViewModel>();
        collection.AddTransient<VoiceSettingsViewModel>();
        collection.AddTransient<WhisperAdvancedViewModel>();
        collection.AddTransient<WhisperPostProcessingViewModel>();
    }
}